name: Build and Deploy Qt App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.5.0
        modules: qtbase, qttools
        host: windows

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make

    - name: Configure and Build
      run: |
        cmake -G "MinGW Makefiles" -B build_windows -DCMAKE_BUILD_TYPE=Release
        cmake --build build_windows --target all --config Release

    - name: Package Application
      run: |
        cmake --install build_windows --prefix package
        windeployqt --dir package build_windows/matrix_calculator.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MatrixCalculator
        path: package