name: Matrix Calculator CI

on:
  push:
    branches: [ MinGW-GitHub ]
  pull_request:
    branches: [ MinGW-GitHub ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        tools: 'tools_mingw90'
        
    - name: Set up CMake
      uses: lukka/get-cmake@latest
      
    - name: Configure CMake
      run: |
        mkdir build_windows
        cd build_windows
        cmake .. -G "MinGW Makefiles" `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_CXX_FLAGS="-fpermissive" `
          -DCMAKE_CXX_STANDARD=17
      shell: pwsh
      
    - name: Build
      run: |
        cd build_windows
        cmake --build . --config Release
        if ($LASTEXITCODE -ne 0) {
          exit $LASTEXITCODE
        }
      shell: pwsh
        
    - name: Check build output
      run: |
        cd build_windows
        Get-ChildItem -Recurse -Filter *.exe
      shell: pwsh
        
    - name: Deploy Qt
      run: |
        cd build_windows
        
        # 1. 设置环境变量
        $env:PATH = "${{ env.Qt6_DIR }}\bin;$env:PATH"
        $env:QT_PLUGIN_PATH = "${{ env.Qt6_DIR }}\plugins"
        
        # 2. 创建必要的目录
        New-Item -ItemType Directory -Force -Path "platforms"
        New-Item -ItemType Directory -Force -Path "styles"
        New-Item -ItemType Directory -Force -Path "imageformats"
        
        # 3. 复制必要的 DLL 文件
        # Qt 核心 DLL
        Copy-Item "${{ env.Qt6_DIR }}\bin\Qt6Core.dll" .
        Copy-Item "${{ env.Qt6_DIR }}\bin\Qt6Gui.dll" .
        Copy-Item "${{ env.Qt6_DIR }}\bin\Qt6Widgets.dll" .
        
        # MinGW 运行时
        Copy-Item "${{ env.Qt6_DIR }}\bin\libgcc_s_seh-1.dll" .
        Copy-Item "${{ env.Qt6_DIR }}\bin\libstdc++-6.dll" .
        Copy-Item "${{ env.Qt6_DIR }}\bin\libwinpthread-1.dll" .
        
        # 平台插件
        Copy-Item "${{ env.Qt6_DIR }}\plugins\platforms\qwindows.dll" "platforms\"
        Copy-Item "${{ env.Qt6_DIR }}\plugins\styles\qwindowsvistastyle.dll" "styles\"
        
        # 4. 运行 windeployqt
        & "${{ env.Qt6_DIR }}\bin\windeployqt.exe" `
          --release `
          --no-translations `
          --no-system-d3d-compiler `
          --no-virtualkeyboard `
          --no-quick-import `
          --force `
          --verbose 2 `
          matrix_calculator.exe
        
        # 5. 检查文件
        Write-Host "Deployed files:"
        Get-ChildItem -Recurse
      shell: pwsh

    - name: List deployed files
      run: |
        cd build_windows
        Get-ChildItem -Recurse
      shell: pwsh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: matrix-calculator-windows
        path: |
          build_windows/*.exe
          build_windows/*.dll
          build_windows/platforms/
          build_windows/styles/
          build_windows/imageformats/